const SET_INPUT = "SET_INPUT";
const SET_SUBMIT = "SET_SUBMIT";
const SET_DELETE = "SET_DELETE";
const SET_FIGHTINGTEXT = "SET_FIGHTINGTEXT";
const SET_EDIT = "SET_EDIT";
const CHANGE_TEXT = "CHANGE_TEXT";
const HANDLE_COMPLETE = "HANDLE_COMPLETE";
const TIME_CHECK = "TIME_CHECK";
const START_TIMER = "START_TIMER";
const UPDATE_TIMER = "UPDATE_TIMER";
const RESET_TIME = "RESET_TIME";

export {
  SET_INPUT,
  SET_SUBMIT,
  SET_DELETE,
  SET_FIGHTINGTEXT,
  SET_EDIT,
  CHANGE_TEXT,
  HANDLE_COMPLETE,
  TIME_CHECK,
  START_TIMER,
  UPDATE_TIMER,
  RESET_TIME
};
