const SET_INPUT = "SET_INPUT";
const SET_SUBMIT = "SET_SUBMIT";
const SET_DELETE = "SET_DELETE";
const SET_FIGHTINGTEXT = "SET_FIGHTINGTEXT";
const SET_EDIT = "SET_EDIT";

export { SET_INPUT, SET_SUBMIT, SET_DELETE, SET_FIGHTINGTEXT, SET_EDIT };
